name: Deploy da Versão de Produção no Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
  VERCEL_PROJECT_ID: ${{ secrets.project_id }}
  VERCEL_TOKEN: ${{ secrets.vercel_token}}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Buildando o site em modo de produção
        run: npm run build

      - name: Instalar o CLI vercel
        run: npm install --global vercel@latest

      - name: Buildando artefatos projeto
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy dos artefatos do projeto
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
